# Generated by Django 4.2.4 on 2023-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterModelTable(
            name='questions',
            table='quiz',
        ),
        migrations.DeleteModel(
            name='Scorebord',
        ),
    ]
